name: CTF Hacker
description: Spreading the knowledge
meta_description: Spreading the knowledge

highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ctfhacker.github.io'
google_analytics: 'UA-67280590-1'

# Details for the RSS feed generator
url:            'www.ctfhacker.com'
author:         'Cory Duplantis'
gems:
  - jekyll-feed
# - jekyll-paginate
# kramdown:
    # input: GFM
    # syntax_highlighter: rogue
