name: CTF Hacker
description: CTF Writeups, Security, Stuff
meta_description: Hack the planet

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://thebarbershopper.github.io'
google_analytics: 'UA-67280590-1'

# Details for the RSS feed generator
url:            'blog url'
author:         'Cory Duplantis'
